In [1]:
import torch
import torch.nn as nn
import torchtext
from torchtext import data
from torchtext.vocab import Vectors
from torchtext.data import Iterator, BucketIterator
import spacy
import numpy as np

In [2]:
nlp = spacy.load('en_core_web_sm')

In [3]:
tokenize = lambda x: [tok.text for tok in nlp.tokenizer(x)]

In [4]:
tokenize('Bozun is the strongest!')

['Bozun', 'is', 'the', 'strongest', '!']

In [5]:
TEXT = data.Field(sequential=True, tokenize=tokenize, lower=True, fix_length=200)
LABEL = data.Field(sequential=False, use_vocab=False)

In [8]:
TEXT.vocab.stoi

AttributeError: 'Field' object has no attribute 'vocab'

In [9]:
LABEL.vocab.stoi

AttributeError: 'Field' object has no attribute 'vocab'

In [6]:
fields = [("id", None), ("phrase", TEXT), ("sentiment", LABEL)]
examples = []

In [7]:
example1 = data.Example.fromlist([None, 'No one is stronger than Bozun!', 5], fields)

In [11]:
example1

In [12]:
dir(example1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'fromCSV',
 'fromJSON',
 'fromdict',
 'fromlist',
 'fromtree',
 'phrase',
 'sentiment']

In [25]:
len(example1.phrase)

7

In [13]:
example1.phrase

['no', 'one', 'is', 'stronger', 'than', 'bozun', '!']

In [14]:
example1.sentiment

5

In [15]:
example1.fromCSV

<bound method Example.fromCSV of <class 'torchtext.data.example.Example'>>

In [16]:
example1.fromCSV()

TypeError: fromCSV() missing 2 required positional arguments: 'data' and 'fields'

In [17]:
example1.__class__

torchtext.data.example.Example

In [20]:
example1.get_attribute('phrase')

AttributeError: 'Example' object has no attribute 'get_attribute'

In [21]:
example1.phrase

['no', 'one', 'is', 'stronger', 'than', 'bozun', '!']

In [8]:
example2 = data.Example.fromlist([None, 'Bozun is the strongest!', 3], fields)

In [26]:
example2

In [27]:
example2.phrase

['bozun', 'is', 'the', 'strongest', '!']

In [28]:
example2.sentiment

3

In [9]:
examples = [example1, example2]

In [10]:
examples

In [11]:
fields

[('id', None),
 ('phrase', <torchtext.data.field.Field at 0x7fc9eab17210>),
 ('sentiment', <torchtext.data.field.Field at 0x7fc9eab170d0>)]

In [10]:
cur_dataset = data.Dataset(examples, fields)

In [15]:
TEXT.vocab.stoi

AttributeError: 'Field' object has no attribute 'vocab'

In [36]:
type(cur_dataset)

torchtext.data.dataset.Dataset

In [40]:
from torch.utils.data import Dataset

In [42]:
issubclass(cur_dataset, Dataset)

TypeError: issubclass() arg 1 must be a class

In [43]:
issubclass(data.Dataset, Dataset)

True

In [44]:
dir(cur_dataset)

['__add__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'download',
 'examples',
 'fields',
 'filter_examples',
 'sort_key',
 'split',
 'splits']

In [23]:
cur_dataset.sort_key is None

True

In [45]:
cur_dataset.fields

{'id': None,
 'phrase': <torchtext.data.field.Field at 0x7fe345038d50>,
 'sentiment': <torchtext.data.field.Field at 0x7fe345038e90>}

In [46]:
cur_dataset.split

<bound method Dataset.split of <torchtext.data.dataset.Dataset object at 0x7fe347e6e150>>

In [47]:
cur_dataset[0]

In [48]:
len(cur_dataset)

2

In [51]:
for i, example in enumerate(cur_dataset):
    print('i:{i} phrase:{phrase}'.format(i=i, phrase=example.phrase))

i:0 phrase:['no', 'one', 'is', 'stronger', 'than', 'bozun', '!']
i:1 phrase:['bozun', 'is', 'the', 'strongest', '!']


In [53]:
def my_dropout(text, p=0.5):
    text = text.strip().split()
    len_ = len(text)
    indexs = np.random.choice(len_, int(len_ * p))
    for i in indexs:
        text[i] = ''
    return ' '.join(text)

In [58]:
for i in range(3):
    print(my_dropout('bozun is the best!'))

bozun  the 
 is the 
 is  best!


In [59]:
np.random.choice(10, 5)

array([5, 8, 3, 1, 3])

In [60]:
cur_dataset[0].__dict__

{'phrase': ['no', 'one', 'is', 'stronger', 'than', 'bozun', '!'],
 'sentiment': 5}

In [61]:
cur_dataset[1].__dict__

{'phrase': ['bozun', 'is', 'the', 'strongest', '!'], 'sentiment': 3}

In [63]:
!ls -a

.                  .git               README.md
..                 .gitignore         data
.DS_Store          .ipynb_checkpoints nlp_practice.ipynb


In [64]:
!mkdir .vector_cache

In [65]:
!ls -a |grep 'vector'

.vector_cache


In [13]:
from torch.utils.data import DataLoader
issubclass(Iterator, DataLoader)

False

In [70]:
for idx, batch in enumerate(cur_iterator):
    print(idx)
    print(batch)
    # print(dir(batch))

AttributeError: 'Field' object has no attribute 'vocab'

In [13]:
cur_dataset

In [11]:
vectors = Vectors(name='glove.6B.50d.txt')
vectors.unk_init = nn.init.xavier_uniform_

In [12]:
vectors

In [19]:
dir(vectors)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'cache',
 'dim',
 'get_vecs_by_tokens',
 'itos',
 'stoi',
 'unk_init',
 'vectors']

In [18]:
len(vectors.stoi)

400000

In [20]:
len(vectors.itos)

400000

In [21]:
vectors.itos[:10]

['the', ',', '.', 'of', 'to', 'and', 'in', 'a', '"', "'s"]

In [22]:
type(vectors.stoi)

dict

In [20]:
vectors.dim

50

In [21]:
type(vectors.vectors)

torch.Tensor

In [22]:
vectors.vectors.shape

torch.Size([400000, 50])

In [16]:
vectors.unk_init

<function torch.nn.init._make_deprecate.<locals>.deprecated_init(*args, **kwargs)>

In [24]:
TEXT

In [25]:
dir(TEXT)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'batch_first',
 'build_vocab',
 'dtype',
 'dtypes',
 'eos_token',
 'fix_length',
 'ignore',
 'include_lengths',
 'init_token',
 'is_target',
 'lower',
 'numericalize',
 'pad',
 'pad_first',
 'pad_token',
 'postprocessing',
 'preprocess',
 'preprocessing',
 'process',
 'sequential',
 'stop_words',
 'tokenize',
 'tokenizer_args',
 'truncate_first',
 'unk_token',
 'use_vocab',
 'vocab_cls']

In [13]:
TEXT.build_vocab(cur_dataset, vectors=vectors)

In [24]:
for idx, vec in enumerate(vectors):
    print(idx)
    print(vec)
    if idx > 1:
        break

0
tensor([-1.0900e-01,  1.4379e-01, -1.3842e-02, -2.9758e-01, -1.5713e-02,
         6.2093e-02,  2.7374e-01, -2.8280e-01,  1.7732e-01,  1.9809e-01,
         2.8066e-01, -2.8645e-01, -2.5411e-01, -3.6886e-02,  2.6745e-01,
        -1.4047e-01, -2.9717e-01, -2.6097e-01,  1.0374e-01,  3.3987e-01,
         1.4899e-01, -1.1863e-01,  1.5165e-01, -1.3671e-01, -9.0084e-02,
         1.3994e-01, -3.2080e-02,  1.1417e-04, -1.2006e-01,  2.1588e-02,
         3.3463e-01, -2.1700e-01, -4.3259e-02,  2.3457e-01, -2.5651e-01,
        -4.9023e-02, -1.3113e-01, -2.8002e-01,  3.1701e-01,  1.2685e-02,
        -2.8102e-02, -3.3500e-01, -1.5457e-01, -2.0662e-01, -2.4349e-01,
        -2.0543e-02, -1.7487e-01,  2.7521e-01,  1.7281e-01, -1.1454e-01])
1
tensor([-0.2337, -0.0628, -0.2699,  0.1672, -0.0488,  0.0344,  0.2381, -0.3046,
         0.2794,  0.2927, -0.2246, -0.3323,  0.2340, -0.2915,  0.3123, -0.2465,
        -0.1248, -0.3213, -0.1058, -0.0706, -0.0230, -0.3191,  0.2060,  0.0436,
        -0.1063,  0.2338,

In [23]:
type(TEXT.vocab.vectors)

torch.Tensor

In [24]:
TEXT.vocab.vectors.shape

torch.Size([11, 50])

In [25]:
dir(cur_dataset)

['__add__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'download',
 'examples',
 'fields',
 'filter_examples',
 'sort_key',
 'split',
 'splits']

In [25]:
TEXT.vocab.freqs

Counter({'no': 1,
         'one': 1,
         'is': 2,
         'stronger': 1,
         'than': 1,
         'bozun': 2,
         '!': 2,
         'the': 1,
         'strongest': 1})

In [27]:
cur_dataset[0].phrase

['no', 'one', 'is', 'stronger', 'than', 'bozun', '!']

In [26]:
TEXT.vocab.itos

['<unk>',
 '<pad>',
 '!',
 'bozun',
 'is',
 'no',
 'one',
 'stronger',
 'strongest',
 'than',
 'the']

In [27]:
print(TEXT.vocab.stoi)

defaultdict(<bound method Vocab._default_unk_index of <torchtext.vocab.Vocab object at 0x7fcf60f559d0>>, {'<unk>': 0, '<pad>': 1, '!': 2, 'bozun': 3, 'is': 4, 'no': 5, 'one': 6, 'stronger': 7, 'strongest': 8, 'than': 9, 'the': 10})


In [39]:
LABEL.vocab.stoi

AttributeError: 'Field' object has no attribute 'vocab'

In [30]:
TEXT.vocab.vectors[1]

tensor([ 0.2441, -0.1991, -0.2887, -0.1345, -0.0980,  0.0599, -0.1198,  0.0038,
         0.1161, -0.0822,  0.0353, -0.2975,  0.3090,  0.1220, -0.1404, -0.0733,
         0.2332, -0.3254, -0.0365,  0.2765, -0.0795, -0.0967, -0.2358,  0.3429,
         0.1782, -0.3360,  0.0644,  0.3099,  0.0759, -0.1444,  0.0852, -0.1978,
        -0.2047, -0.1389,  0.1850,  0.0068,  0.0602, -0.2276,  0.2837,  0.3052,
        -0.1379,  0.0994,  0.0490,  0.2826, -0.2327,  0.2530, -0.3146, -0.1027,
         0.0597, -0.1187])

In [15]:
cur_iterator = BucketIterator(dataset=cur_dataset, batch_size=1, shuffle=True, sort_within_batch=False, repeat=False)
cur_iterator

In [20]:
LABEL.use_vocab

False

In [21]:
LABEL.vocab.vectors

In [38]:
for idx, batch in enumerate(cur_iterator):
    print(batch.phrase.shape)
    if idx == 0:
        break

torch.Size([200, 1])


In [39]:
batch = next(iter(cur_iterator))

In [40]:
type(batch)

torchtext.data.batch.Batch

In [41]:
dir(batch)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_field_values',
 'batch_size',
 'dataset',
 'fields',
 'fromvars',
 'input_fields',
 'phrase',
 'sentiment',
 'target_fields']

In [42]:
batch.dataset

In [43]:
batch.dataset[0]

In [44]:
len(batch.dataset)

2

In [45]:
batch.sentiment

tensor([5])

In [47]:
batch


[torchtext.data.batch.Batch of size 1]
	[.phrase]:[torch.LongTensor of size 200x1]
	[.sentiment]:[torch.LongTensor of size 1]

In [51]:
TEXT.vocab.itos[batch.phrase[batch.phrase != 1]]

TypeError: only integer tensors of a single element can be converted to an index

In [52]:
batch.phrase[batch.phrase != 1]

tensor([5, 6, 4, 7, 9, 3, 2])

In [16]:
TEXT.vocab.itos

['<unk>',
 '<pad>',
 '!',
 'bozun',
 'is',
 'no',
 'one',
 'stronger',
 'strongest',
 'than',
 'the']

In [55]:
np.asarray(batch.phrase[batch.phrase != 1])

array([5, 6, 4, 7, 9, 3, 2])

In [58]:
np.asarray(TEXT.vocab.itos)[batch.phrase[batch.phrase != 1]]

array(['no', 'one', 'is', 'stronger', 'than', 'bozun', '!'], dtype='<U9')

In [59]:
TEXT.fix_length

200

In [17]:
LABEL.vocab

In [62]:
cur_iterator.sort_key is None

True

In [63]:
example1.phrase

['no', 'one', 'is', 'stronger', 'than', 'bozun', '!']

In [64]:
dir(vectors)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'cache',
 'dim',
 'get_vecs_by_tokens',
 'itos',
 'stoi',
 'unk_init',
 'vectors']

In [65]:
len(TEXT.vocab)

11

In [14]:
LABEL.build_vocab(cur_dataset)

In [67]:
LABEL.vocab

In [68]:
LABEL.vocab.itos

['<unk>', 3, 5]

In [18]:
LABEL.vocab.vectors

In [19]:
len(LABEL.vocab)

3

In [71]:
TEXT.vocab.vectors.size()

torch.Size([11, 50])

In [73]:
TEXT.vocab.vectors.size(1)

50

In [74]:
temp = nn.Embedding(4, 3)

In [76]:
temp.weight.requires_grad

True

In [78]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [79]:
train_path = 'data/sentiment-analysis-on-movie-reviews/train.tsv'
test_path = 'data/sentiment-analysis-on-movie-reviews/test.tsv'

In [80]:
train=pd.read_csv(train_path, sep='\t')

In [81]:
type(train)

pandas.core.frame.DataFrame

In [83]:
test = pd.read_csv(test_path, sep='\t')

In [98]:
origin_data = train[['PhraseId', 'SentenceId', 'Phrase']]
origin_label = train[['Sentiment']]

In [101]:
train_data, val_data, train_label, val_label = train_test_split(
                                            origin_data, origin_label, test_size=0.2, random_state=0)

In [122]:
len(train_data)

124848

In [134]:
i = 0
for cur_data in train_data.itertuples():
    print(type(cur_data.Phrase))
    i += 1
    if i > 1:
        break

<class 'str'>
<class 'str'>


In [125]:
train_data.head(5)

PhraseId  SentenceId  \
7739        7740         314   
150007    150008        8169   
81245      81246        4189   
3322        3323         125   
28666      28667        1327   

                                                   Phrase  
7739                                   breaking codes and  
150007           under the weight of too many story lines  
81245   Daringly perceptive , taut , piercing and feis...  
3322                                               honest  
28666   is grand-scale moviemaking for a larger-than-l...

In [108]:
train_label.head(5)

Sentiment
7739            2
150007          1
81245           3
3322            4
28666           4

In [105]:
len(train_data) + len(val_data) == len(origin_data)

True

In [104]:
len(val_data)

31212

In [95]:
len(train)

156060

In [106]:
len(test)

66292

In [107]:
len(train_data) / len(val_data) 

4.0

In [110]:
pd.concat([train_data, train_label]).head(5)

PhraseId  SentenceId  \
7739      7740.0       314.0   
150007  150008.0      8169.0   
81245    81246.0      4189.0   
3322      3323.0       125.0   
28666    28667.0      1327.0   

                                                   Phrase  Sentiment  
7739                                   breaking codes and        NaN  
150007           under the weight of too many story lines        NaN  
81245   Daringly perceptive , taut , piercing and feis...        NaN  
3322                                               honest        NaN  
28666   is grand-scale moviemaking for a larger-than-l...        NaN

In [111]:
len(train_data) == len(train_label)

True

In [113]:
pd.merge(train_data, train_label, left_index=True, right_index=True).head(5)

PhraseId  SentenceId  \
7739        7740         314   
150007    150008        8169   
81245      81246        4189   
3322        3323         125   
28666      28667        1327   

                                                   Phrase  Sentiment  
7739                                   breaking codes and          2  
150007           under the weight of too many story lines          1  
81245   Daringly perceptive , taut , piercing and feis...          3  
3322                                               honest          4  
28666   is grand-scale moviemaking for a larger-than-l...          4

In [114]:
train_final = pd.merge(train_data, train_label, left_index=True, right_index=True)
val_final = pd.merge(val_data, val_label, left_index=True, right_index=True)

In [115]:
len(train_final)

124848

In [116]:
len(val_final)

31212

In [118]:
len(train_final) + len(val_final) == len(train)

True

In [120]:
data_path = 'data/sentiment-analysis-on-movie-reviews/'
train_final.to_csv(data_path + 'train.csv', index=False)
val_final.to_csv(data_path + 'val.csv', index=False)
test.to_csv(data_path + 'test.csv', index=False)

In [121]:
len(test)

66292

In [26]:
a = torch.randn((3, 2))

In [27]:
a

tensor([[-0.6968, -0.3865],
        [ 0.2027, -1.3358],
        [ 0.3049,  1.4762]])

In [30]:
a.permute(1, 0).shape

torch.Size([2, 3])

In [31]:
a.shape

torch.Size([3, 2])

In [32]:
a.shape[1]

2

In [4]:
inputs = [torch.randn(1, 3) for _ in range(5)]

In [5]:
inputs = torch.cat(inputs).view(len(inputs), 1, -1)

In [6]:
inputs.shape

torch.Size([5, 1, 3])

In [8]:
batch_size=3
hidden_size=5
embedding_dim=6
seq_length=4
num_layers=1
num_directions=1
vocab_size=20

input_data=np.random.uniform(0,19,size=(batch_size,seq_length))
input_data=torch.from_numpy(input_data).long()
embedding_layer=nn.Embedding(vocab_size,embedding_dim)
lstm_layer=nn.LSTM(input_size=embedding_dim,hidden_size=hidden_size,num_layers=num_layers,
                        bias=True,batch_first=False,dropout=0,bidirectional=False)
lstm_input=embedding_layer(input_data)
assert lstm_input.shape==(batch_size,seq_length,embedding_dim)
lstm_input.transpose_(1,0)
assert lstm_input.shape==(seq_length,batch_size,embedding_dim)
output,(h_n,c_n)=lstm_layer(lstm_input)
assert output.shape==(seq_length,batch_size,hidden_size)
assert h_n.shape==c_n.shape==(num_layers*num_directions,batch_size,hidden_size)

In [10]:
output.shape

torch.Size([4, 3, 5])

In [11]:
output[-1].shape

torch.Size([3, 5])

In [12]:
h_n.shape

torch.Size([1, 3, 5])

In [13]:
c_n.shape

torch.Size([1, 3, 5])

In [15]:
lstm_input.shape

torch.Size([4, 3, 6])

In [16]:
output[-1]

tensor([[ 0.1550,  0.1347,  0.0396,  0.0042, -0.1769],
        [-0.3279,  0.2663, -0.0629,  0.1781, -0.1144],
        [ 0.3068,  0.2045, -0.4523, -0.3939,  0.0283]],
       grad_fn=<SelectBackward>)

In [17]:
h_n

tensor([[[ 0.1550,  0.1347,  0.0396,  0.0042, -0.1769],
         [-0.3279,  0.2663, -0.0629,  0.1781, -0.1144],
         [ 0.3068,  0.2045, -0.4523, -0.3939,  0.0283]]],
       grad_fn=<StackBackward>)

In [18]:
h_n.new_zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
h_n.shape

torch.Size([1, 3, 5])

In [23]:
torch.max(h_n.squeeze(0), dim=1)[-1]

tensor([0, 1, 0])

In [21]:
h_n.squeeze(0).shape

torch.Size([3, 5])

In [27]:
h_n[0, 0].tolist()

[0.15496273338794708,
 0.1346675604581833,
 0.039612218737602234,
 0.004196253605186939,
 -0.17688137292861938]

In [28]:
a = torch.rand(3)
a

tensor([0.1090, 0.9065, 0.6446])

In [29]:
b = torch.rand(3)

In [31]:
a.shape

torch.Size([3])

In [32]:
torch.cat([a, b], dim=0)

tensor([0.1090, 0.9065, 0.6446, 0.1788, 0.1073, 0.6507])